on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  local-build-job:
    runs-on: self-hosted
    steps:
      - name: Move Files
        run: |
          mkdir -p /tmp/GoMining-Bot
          if [ -f .env ]; then
            mv .env /tmp/GoMining-Bot/
          fi

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Restore Files
        run: |
          if [ -f /tmp/GoMining-Bot/.env ]; then
            mv /tmp/GoMining-Bot/.env .
          fi
          rm -rf /tmp/GoMining-Bot
      
      - name: Build Docker Container
        run: docker compose build

      - name: Restart Docker Container
        run: |
          docker compose down
          docker compose up -d

      - name: Clean Up Docker Images and Build Cache
        run: |
          docker image prune -f
          docker builder prune -f
