on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  local-build-job:
    runs-on: self-hosted
    steps:
      - name: Move Files
        run: |
          mkdir -p /tmp/GoMining-Bot
          if [ -f .env ]; then
            mv .env /tmp/GoMining-Bot/
            echo ".env file moved to /tmp/GoMining-Bot"
          fi

      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Restore Files
        run: |
          mv /tmp/GoMining-Bot/.* .
          rm -rf /tmp/GoMining-Bot
          echo "Files restored"
      
      - name: Rebuild Docker Container
        run: |
          docker compose down
          docker compose build
          docker compose up -d
